# Generated by Django 4.2 on 2024-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_entry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
