# Generated by Django 4.2 on 2024-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_entry_app', '0002_alter_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
